augmenter_model: v0.3
bbox_thr: 0.8
camerasToUse:
- all
filterFrequency: default
imageUpsampleFactor: 4
openSimModel: LaiUhlrich2022
poseDetector: mmpose
scalingSetup: upright_standing_pose
verticalOffset: -0.12756856914520265
