---
title: "TurnerShoulderAnalysis"
author: "Jeffrey Turner"
date: "2024-04-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Clearing R environment}
rm(list=ls())
```

```{r Library}
library(signal)
library(psych)
library(tidyr)
library(readr)
library(ggplot2)
library(blandr)
library(dplyr)
library(cowplot)
library(gridExtra)
library(pracma)
library(ggpmisc)
```

```{r}

directory <- "~/Documents/GitHub/opencap-processing/Projects/Shoulder/OpenCapData_78b1e354-e4cd-4f1e-848b-5c5ad2b015f1/OpenSimData/Kinematics/"

# List all files in the directory
files <- list.files(directory, full.names = TRUE)

# Week 6
desired_file <- grep("shoulder_flexion_w6\\.mot$", files, value = TRUE)
motion <- read.table(desired_file, skip = 10, header = TRUE, sep = "\t")
cutoff_freq <- 10
sampling_freq <- 1 / mean(diff(motion$time))  
filter_coef <- butter(4, cutoff_freq / (sampling_freq / 2), type = "low")
filtered_motion <- motion
filtered_motion[, -1] <- apply(filtered_motion[, -1], 2, function(x) filter(filter_coef, x))
time <- filtered_motion$time
w6_right <- filtered_motion$arm_flex_r
w6_left <- filtered_motion$arm_flex_l
plot(w6_left)

# Week 7
desired_file <- grep("shoulder_flexion_w7\\.mot$", files, value = TRUE)
motion <- read.table(desired_file, skip = 10, header = TRUE, sep = "\t")
cutoff_freq <- 10
sampling_freq <- 1 / mean(diff(motion$time))  
filter_coef <- butter(4, cutoff_freq / (sampling_freq / 2), type = "low")
filtered_motion <- motion
filtered_motion[, -1] <- apply(filtered_motion[, -1], 2, function(x) filter(filter_coef, x))
#filtered_motion <- head(filtered_motion, -23)  
w7_right <- filtered_motion$arm_flex_r
w7_left <- filtered_motion$arm_flex_l
plot(w7_left)

# Week 8
desired_file <- grep("shoulder_flexion_w8\\.mot$", files, value = TRUE)
motion <- read.table(desired_file, skip = 10, header = TRUE, sep = "\t")
cutoff_freq <- 10
sampling_freq <- 1 / mean(diff(motion$time))  
filter_coef <- butter(4, cutoff_freq / (sampling_freq / 2), type = "low")
filtered_motion <- motion
filtered_motion[, -1] <- apply(filtered_motion[, -1], 2, function(x) filter(filter_coef, x))
#filtered_motion <- head(filtered_motion, -21) 
w8_right <- filtered_motion$arm_flex_r
w8_left <- filtered_motion$arm_flex_l
plot(w8_left)

# Week 9
desired_file <- grep("shoulder_flexion_w9\\.mot$", files, value = TRUE)
motion <- read.table(desired_file, skip = 10, header = TRUE, sep = "\t")
cutoff_freq <- 10
sampling_freq <- 1 / mean(diff(motion$time))  
filter_coef <- butter(4, cutoff_freq / (sampling_freq / 2), type = "low")
filtered_motion <- motion
filtered_motion[, -1] <- apply(filtered_motion[, -1], 2, function(x) filter(filter_coef, x))
w9_right <- filtered_motion$arm_flex_r
w9_left <- filtered_motion$arm_flex_l
plot(w9_left)


# Week 10
desired_file <- grep("shoulder_flexion_w10\\.mot$", files, value = TRUE)
motion <- read.table(desired_file, skip = 10, header = TRUE, sep = "\t")
cutoff_freq <- 10
sampling_freq <- 1 / mean(diff(motion$time))  
filter_coef <- butter(4, cutoff_freq / (sampling_freq / 2), type = "low")
filtered_motion <- motion
filtered_motion[, -1] <- apply(filtered_motion[, -1], 2, function(x) filter(filter_coef, x))
#filtered_motion <- head(filtered_motion, -82)  # Remove the last 10 rows
w10_right <- filtered_motion$arm_flex_r
w10_left <- filtered_motion$arm_flex_l
plot(w10_left)
# Week 11
desired_file <- grep("shoulder_flexion_w11\\.mot$", files, value = TRUE)
motion <- read.table(desired_file, skip = 10, header = TRUE, sep = "\t")
cutoff_freq <- 10
sampling_freq <- 1 / mean(diff(motion$time))  
filter_coef <- butter(4, cutoff_freq / (sampling_freq / 2), type = "low")
filtered_motion <- motion
filtered_motion[, -1] <- apply(filtered_motion[, -1], 2, function(x) filter(filter_coef, x))
#filtered_motion <- head(filtered_motion, -149)  # Remove the last 10 rows
w11_right <- filtered_motion$arm_flex_r
w11_left <- filtered_motion$arm_flex_l
plot(w11_left)

# Week 12
desired_file <- grep("shoulder_flexion_w12_1\\.mot$", files, value = TRUE)
motion <- read.table(desired_file, skip = 10, header = TRUE, sep = "\t")
cutoff_freq <- 10
sampling_freq <- 1 / mean(diff(motion$time))  
filter_coef <- butter(4, cutoff_freq / (sampling_freq / 2), type = "low")
filtered_motion <- motion
filtered_motion[, -1] <- apply(filtered_motion[, -1], 2, function(x) filter(filter_coef, x))
#filtered_motion <- head(filtered_motion, -348) 
w12_right <- filtered_motion$arm_flex_r
w12_left <- filtered_motion$arm_flex_l
plot(w12_left)



# Create a data frame for plotting
plot_data <- data.frame(w6_right = w6_right, w6_left = w6_left, 
                        w7_left = w7_left, w8_left = w8_left, w9_left = w9_left,
                        w10_left = w10_left, w11_left = w11_left, w12_left = w12_left)

# Plot arm flexion for both arms in the same plot
ggplot(plot_data, aes(x = time)) +
  geom_line(aes(y = w6_right, color = "Unaffected Arm")) +
  geom_line(aes(y = w6_left, color = "Week 6")) +
  geom_line(aes(y = w7_left, color = "Week 7")) +
  geom_line(aes(y = w8_left, color = "Week 8")) +
  geom_line(aes(y = w9_left, color = "Week 9")) +
  geom_line(aes(y = w10_left, color = "Week 10")) +
  geom_line(aes(y = w11_left, color = "Week 11")) +
  geom_line(aes(y = w12_left, color = "Week 12")) +
  labs(x = "Time", y = "Shoulder Flexion", color = "Arm") +
  ggtitle("Shoulder Flexion for Right and Left Arms") +  
  scale_y_continuous(breaks = seq(min(0), 
                                   max(200), 
                                   by = 25)) +
  theme_minimal()
```

```{r}

library(ggplot2)
library(signal)

# Function to resample time series data
resample_time_series <- function(time, data, new_length) {
  new_time <- seq(min(time), max(time), length.out = new_length)
  new_data <- approx(time, data, new_time)$y
  return(list(new_time = new_time, new_data = new_data))
}

directory <- "~/Documents/GitHub/opencap-processing/Projects/Shoulder/OpenCapData_78b1e354-e4cd-4f1e-848b-5c5ad2b015f1/OpenSimData/Kinematics/"

# List all files in the directory
files <- list.files(directory, full.names = TRUE)

# Function to read and preprocess motion data
read_and_preprocess <- function(file_path, cutoff_freq = 10, skip_rows = 10, trim_rows = 0) {
  motion <- read.table(file_path, skip = skip_rows, header = TRUE, sep = "\t")
  sampling_freq <- 1 / mean(diff(motion$time))  
  filter_coef <- butter(4, cutoff_freq / (sampling_freq / 2), type = "low")
  filtered_motion <- motion
  filtered_motion[, -1] <- apply(filtered_motion[, -1], 2, function(x) filter(filter_coef, x))
  if (trim_rows > 0) {
    filtered_motion <- head(filtered_motion, -trim_rows)
  }
  return(filtered_motion)
}

# Read and preprocess motion data for Week 6
desired_file <- grep("shoulder_flexion_w6\\.mot$", files, value = TRUE)
motion <- read_and_preprocess(desired_file)
time <- motion$time
w6_right <- motion$arm_flex_r
w6_left <- motion$arm_flex_l
new_length <- 400
resampled_data_right <- resample_time_series(time, w6_right, new_length)
resampled_data_left <- resample_time_series(time, w6_left, new_length)
plot(resampled_data_left$new_data)

desired_file <- grep("shoulder_flexion_w7\\.mot$", files, value = TRUE)
motion <- read_and_preprocess(desired_file)
time <- motion$time
w7_right <- motion$arm_flex_r
w7_left <- motion$arm_flex_l
new_length <- 400
resampled_data_left7 <- resample_time_series(time, w7_left, new_length)
plot(resampled_data_left7$new_data)

desired_file <- grep("shoulder_flexion_w8\\.mot$", files, value = TRUE)
motion <- read_and_preprocess(desired_file)
time <- motion$time
w8_right <- motion$arm_flex_r
w8_left <- motion$arm_flex_l
new_length <- 400
resampled_data_left8 <- resample_time_series(time, w8_left, new_length)
plot(resampled_data_left8$new_data)

desired_file <- grep("shoulder_flexion_w9\\.mot$", files, value = TRUE)
motion <- read_and_preprocess(desired_file)
time <- motion$time
w9_right <- motion$arm_flex_r
w9_left <- motion$arm_flex_l
new_length <- 400
resampled_data_left9 <- resample_time_series(time, w9_left, new_length)
plot(resampled_data_left9$new_data)

desired_file <- grep("shoulder_flexion_w10\\.mot$", files, value = TRUE)
motion <- read_and_preprocess(desired_file)
time <- motion$time
w10_right <- motion$arm_flex_r
w10_left <- motion$arm_flex_l
new_length <- 400
resampled_data_left10 <- resample_time_series(time, w10_left, new_length)
plot(resampled_data_left10$new_data)

desired_file <- grep("shoulder_flexion_w11\\.mot$", files, value = TRUE)
motion <- read_and_preprocess(desired_file)
time <- motion$time
w11_right <- motion$arm_flex_r
w11_left <- motion$arm_flex_l
new_length <- 400
resampled_data_left11 <- resample_time_series(time, w11_left, new_length)
plot(resampled_data_left11$new_data)

desired_file <- grep("shoulder_flexion_w12_1\\.mot$", files, value = TRUE)
motion <- read_and_preprocess(desired_file)
time <- motion$time
w12_right <- motion$arm_flex_r
w12_left <- motion$arm_flex_l
new_length <- 400
resampled_data_left12 <- resample_time_series(time, w12_left, new_length)
plot(resampled_data_left12$new_data)

plot_data <- data.frame(time = resampled_data_right$new_time, 
                        w6_right = resampled_data_right$new_data, 
                        w6_left = resampled_data_left$new_data,
                        w7_left = resampled_data_left7$new_data,
                        w8_left = resampled_data_left8$new_data,
                        w9_left = resampled_data_left9$new_data,
                        w10_left = resampled_data_left10$new_data,
                        w11_left = resampled_data_left11$new_data,
                        w12_left = resampled_data_left12$new_data)

legend_order <- c("Unaffected Arm","Week 12", "Week 11", "Week 10", "Week 9", "Week 8", "Week 7", "Week 6")
legend_colors <- c("Unaffected Arm" = "black","Week 12" = "green", "Week 11" = "forestgreen", 
                   "Week 10" = "darkgreen", "Week 9" = "yellow", "Week 8" = "darkorange", 
                   "Week 7" = "red","Week 6" = "darkred")

ggplot(plot_data, aes(x = time)) +
  geom_line(aes(y = w6_right, color = "Unaffected Arm"), size = 1.5) +
  geom_line(aes(y = w6_left, color = "Week 6")) +
  geom_line(aes(y = w7_left, color = "Week 7")) +
  geom_line(aes(y = w8_left, color = "Week 8")) +
  geom_line(aes(y = w9_left, color = "Week 9")) +
  geom_line(aes(y = w10_left, color = "Week 10")) +
  geom_line(aes(y = w11_left, color = "Week 11")) +
  geom_line(aes(y = w12_left, color = "Week 12")) +
  labs(x = "Time", y = "Shoulder Flexion (degrees)", color="") +
  ggtitle("Shoulder Flexion for Right and Left Arms") +  
  scale_y_continuous(breaks = seq(min(0), 
                                   max(200), 
                                   by = 25)) +
  scale_color_manual(values = legend_colors, 
                     breaks = legend_order, 
                     labels = legend_order) +
  theme_minimal()



```

